-- MYSHORT - REAL MINING LEDGER / XMR SWAP
-- Jalankan SETELAH supabase_schema_secure.sql
-- Catatan: database ini hanya menerima kredit XMR dari worker/backend terpercaya.
-- Jangan pernah memberikan service_role key ke browser.

create table if not exists public.mining_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  xmr_balance numeric(30,12) not null default 0 check (xmr_balance >= 0),
  total_mined numeric(30,12) not null default 0 check (total_mined >= 0),
  total_swapped numeric(30,12) not null default 0 check (total_swapped >= 0),
  status text not null default 'stopped' check (status in ('running','stopped','paused')),
  started_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.mining_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  worker_name text,
  status text not null default 'running' check (status in ('running','stopped','paused')),
  started_at timestamptz not null default now(),
  stopped_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists mining_one_running_session
on public.mining_sessions(user_id) where status='running';

create table if not exists public.mining_credits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount_xmr numeric(30,12) not null check (amount_xmr > 0),
  source_ref text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.xmr_rates (
  id bigint generated by default as identity primary key,
  rate_idr numeric(30,2) not null check (rate_idr > 0),
  source text not null,
  observed_at timestamptz not null default now(),
  is_current boolean not null default true
);

create unique index if not exists xmr_one_current_rate
on public.xmr_rates(is_current) where is_current=true;

create table if not exists public.mining_swaps (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount_xmr numeric(30,12) not null check (amount_xmr > 0),
  rate_idr numeric(30,2) not null check (rate_idr > 0),
  amount_idr numeric(30,2) not null check (amount_idr > 0),
  created_at timestamptz not null default now()
);

alter table public.mining_accounts enable row level security;
alter table public.mining_sessions enable row level security;
alter table public.mining_credits enable row level security;
alter table public.xmr_rates enable row level security;
alter table public.mining_swaps enable row level security;

drop policy if exists mining_accounts_select on public.mining_accounts;
create policy mining_accounts_select on public.mining_accounts
for select to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists mining_sessions_select on public.mining_sessions;
create policy mining_sessions_select on public.mining_sessions
for select to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists mining_credits_select on public.mining_credits;
create policy mining_credits_select on public.mining_credits
for select to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists xmr_rates_select on public.xmr_rates;
create policy xmr_rates_select on public.xmr_rates
for select to authenticated using (true);

drop policy if exists mining_swaps_select on public.mining_swaps;
create policy mining_swaps_select on public.mining_swaps
for select to authenticated using (user_id=auth.uid() or public.is_admin());

-- Buat akun mining otomatis untuk member baru.
create or replace function public.ensure_mining_account()
returns trigger
language plpgsql security definer set search_path=public
as $$
begin
  insert into public.mining_accounts(user_id) values(new.id)
  on conflict(user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_profile_mining_account on public.profiles;
create trigger on_profile_mining_account
after insert on public.profiles
for each row execute function public.ensure_mining_account();

-- Backfill akun mining untuk member lama.
insert into public.mining_accounts(user_id)
select id from public.profiles
on conflict(user_id) do nothing;

create or replace function public.start_mining()
returns void
language plpgsql security definer set search_path=public
as $$
declare uid uuid:=auth.uid();
begin
  if uid is null then raise exception 'Belum login'; end if;
  insert into public.mining_accounts(user_id,status,started_at,updated_at)
  values(uid,'running',now(),now())
  on conflict(user_id) do update set status='running',started_at=coalesce(public.mining_accounts.started_at,now()),updated_at=now();

  if exists(select 1 from public.mining_sessions where user_id=uid and status='running') then
    return;
  end if;
  insert into public.mining_sessions(user_id,status,started_at) values(uid,'running',now());
end;
$$;

create or replace function public.stop_mining()
returns void
language plpgsql security definer set search_path=public
as $$
declare uid uuid:=auth.uid();
begin
  if uid is null then raise exception 'Belum login'; end if;
  update public.mining_sessions
  set status='stopped',stopped_at=now()
  where user_id=uid and status='running';
  update public.mining_accounts
  set status='stopped',updated_at=now()
  where user_id=uid;
end;
$$;

-- Hanya worker/backend terpercaya yang boleh menjalankan fungsi ini.
-- source_ref wajib unik sehingga share/payout tidak bisa dikredit dua kali.
create or replace function public.record_mining_credit(
  p_user_id uuid,
  p_amount_xmr numeric,
  p_source_ref text
)
returns bigint
language plpgsql security definer set search_path=public
as $$
declare cid bigint; 
begin
  if p_user_id is null then raise exception 'user_id wajib'; end if;
  if p_amount_xmr <= 0 or p_amount_xmr > 1 then raise exception 'Jumlah XMR tidak valid'; end if;
  if coalesce(trim(p_source_ref),'')='' then raise exception 'source_ref wajib'; end if;

  insert into public.mining_credits(user_id,amount_xmr,source_ref)
  values(p_user_id,p_amount_xmr,p_source_ref)
  on conflict(source_ref) do nothing
  returning id into cid;

  if cid is null then
    select id into cid from public.mining_credits where source_ref=p_source_ref;
    return cid;
  end if;

  insert into public.mining_accounts(user_id)
  values(p_user_id) on conflict(user_id) do nothing;

  update public.mining_accounts
  set xmr_balance=xmr_balance+p_amount_xmr,
      total_mined=total_mined+p_amount_xmr,
      updated_at=now()
  where user_id=p_user_id;

  insert into public.transactions(user_id,type,amount,description)
  values(p_user_id,'mining_xmr_credit',0,'Kredit XMR mining terverifikasi: '||p_source_ref);

  return cid;
end;
$$;

-- Harga XMR harus dimasukkan oleh rate-sync backend, bukan browser/member.
create or replace function public.set_xmr_rate(
  p_rate_idr numeric,
  p_source text
)
returns bigint
language plpgsql security definer set search_path=public
as $$
declare rid bigint;
begin
  if p_rate_idr <= 0 then raise exception 'Rate tidak valid'; end if;
  if coalesce(trim(p_source),'')='' then raise exception 'Source wajib'; end if;
  update public.xmr_rates set is_current=false where is_current=true;
  insert into public.xmr_rates(rate_idr,source,is_current)
  values(p_rate_idr,left(trim(p_source),100),true)
  returning id into rid;
  return rid;
end;
$$;

create or replace function public.swap_mining_xmr(p_amount_xmr numeric)
returns numeric
language plpgsql security definer set search_path=public
as $$
declare uid uuid:=auth.uid();
  acc public.mining_accounts;
  rate public.xmr_rates;
  swap_id bigint;
  idr numeric(30,2);
begin
  if uid is null then raise exception 'Belum login'; end if;
  if p_amount_xmr <= 0 then raise exception 'Jumlah XMR tidak valid'; end if;

  select * into acc from public.mining_accounts where user_id=uid for update;
  if not found then raise exception 'Akun mining tidak ditemukan'; end if;
  if acc.xmr_balance < p_amount_xmr then raise exception 'Saldo XMR tidak mencukupi'; end if;

  select * into rate from public.xmr_rates
  where is_current=true and observed_at >= now()-interval '15 minutes'
  order by observed_at desc limit 1;
  if not found then raise exception 'Kurs XMR sedang tidak tersedia atau sudah kedaluwarsa'; end if;

  idr:=round(p_amount_xmr*rate.rate_idr,2);
  if idr <= 0 then raise exception 'Nilai swap tidak valid'; end if;

  update public.mining_accounts
  set xmr_balance=xmr_balance-p_amount_xmr,
      total_swapped=total_swapped+p_amount_xmr,
      updated_at=now()
  where user_id=uid;

  insert into public.mining_swaps(user_id,amount_xmr,rate_idr,amount_idr)
  values(uid,p_amount_xmr,rate.rate_idr,idr)
  returning id into swap_id;

  update public.wallets
  set balance=balance+idr,total_in=total_in+idr,updated_at=now()
  where user_id=uid;
  if not found then raise exception 'Wallet tidak ditemukan'; end if;

  insert into public.transactions(user_id,type,amount,reference_id,description)
  values(uid,'mining_swap',idr,swap_id,'Swap XMR ke Rupiah pada rate aktual');

  return idr;
end;
$$;

-- Jangan expose fungsi backend ke member.
revoke all on function public.record_mining_credit(uuid,numeric,text) from public,authenticated;
revoke all on function public.set_xmr_rate(numeric,text) from public,authenticated;
grant execute on function public.record_mining_credit(uuid,numeric,text) to service_role;
grant execute on function public.set_xmr_rate(numeric,text) to service_role;

revoke all on function public.start_mining() from public;
revoke all on function public.stop_mining() from public;
grant execute on function public.start_mining() to authenticated;
grant execute on function public.stop_mining() to authenticated;

grant execute on function public.swap_mining_xmr(numeric) to authenticated;
